EntityBundle\Entity\AGBAgreement:
  relations:
    -
      rel: agb
      href:
        route: get_agb
        parameters:
          agbID: expr(object.getAgb().getId())
    -
      rel: exchange
      href:
        route: get_people_exchanges
        parameters:
          personID: expr(object.getExchange().getPerson().getId())
          exchangeID: expr(object.getExchange().getId())
  properties:
    agb:
      exclude: true
    exchange:
      exclude: true
